haiku = [
	'The web page you seek\nLies beyond our perception\nBut others await.',
	'Pages you are seeking\nFrom your path they are fleeing\nTheir winter has come.',
	'A truth found, be told\nYou are far from the fold, Go\nCome back yet again.',
	"Wind catches lily\nScatt'ring petals to the wind:\nYour page is not found.",
	'These three are certain:\nDeath, taxes, and page not found.\nYou, victim of one.',
	'Ephemeral page.\nI am the Blue Screen of Death.\nNo one hears your screams.',
	'Aborted effort:\nThe page, passed this veil of tears.\nYou ask way too much.',
	'Morning and sorrow\n404 not with us now\nLost to paradise.',
	'Not a pretty sight\nWhen the web dies screaming loud\nThe page is not found.',
	'Site slips through fingers\nPulse pounding hard and frantic\nVanishing like mist.',
	'The dream is shattered\nThe web page cannot be found\nInside the spring rain.',
	'Bartender yells loud\nYour page cannot be found, boy\nBuy another drink.',
	"Chrome megaphone barks\nIt's not possible to talk\nNot yet anyway.",
	'Emptyness of soul\nForever aching blackness:\n"404 page not found."',
	'Click exciting link\nGossamer threads hold you back\n404 not found.',
	'With searching comes loss\nAnd the presence of absence:\nThe page is not found.',
	'You step in the stream,\nBut the water has moved on\nThe page is not here.',
	"Rather than a beep\nOr a rude error message,\nThese words: 'Page not found.'",
	'Something you entered\nTranscended parameters.\nThe page is unknown.',
	"There is a chasm\nOf carbon and silicon\nThe server can't bridge.",
	'Site is silent, yes\nNo voices can be heard now\nThe cows roll their eyes.',
	'The ten thousand things\nHow long do any persist?\nThe file, not there.',
	'A file that big?\nIt might be very useful\nBut now it is gone.',
	'To have no errors\nWould be life without meaning\nNo struggle, no joy.',
	'The code was willing\nIt considered your request,\nBut the chips were weak.',
	'Error reduces\nYour expensive computer\nTo a simple stone.'
]
