#!/usr/bin/env python2

"""
Post a single static page at /draft/slug, where the title and body of the page
is extracted from the HTML markup of the given file.

Usage: draft [-l] filepath

By default, requests are made to {APPID}.appspot.com.
The script will print out the URL of the draft page if success.

Options:
    -l    make requests to to localhost:8080
"""
import BeautifulSoup
import datetime
import sys
import os

import remote

if sys.argv[1] == '-l':
	host = 'localhost:8080'
	filename = sys.argv[2]
else:
	host = None
	filename = sys.argv[1]

remote.attach(host)

import config
import models
import static
import utils


soup = BeautifulSoup.BeautifulSoup(open(filename).read())

post = models.BlogPost(
		path='/draft/'+os.path.basename(filename),
		title=unicode(soup.title.string),
		body=u''.join(unicode(s) for s in soup.body.contents if s),
		published=datetime.datetime.now()
	)

rendered = utils.render_template("draft.html", {'post': post})

static.set(post.path, rendered, config.html_mime_type, indexed=False)

print 'http://' + (host or (remote.APPID + '.appspot.com')) + post.path
